### ISSUE TITLE
The .meta file missed.

### ISSUE THREAD

**Issue by Sunrepe** [hecomi/MyoUnity-with-RawData#1]
Hello,thank you for your code~
But I have a question that when i import the project into my unity, all the .meta file have been missed.
Can you tell me why?

**Comment by hecomi** [comment]
Sorry for my late reply..., I think you are not currently working on this but for others I left a comment:
I guess the Unity version with which I created this plugin is very old (v5.0). Or please use the .unitypackage:
https://github.com/hecomi/MyoUnity-with-RawData/raw/master/MyoUnity-with-RawData.unitypackage
